[package]
name = "mpv_stream"
version = "0.3.2"
edition = "2018"

[dependencies]
serde_json = "*"
curl = "*"
libmpv = "2.0.0"
crossbeam = "0.7.3"

[dependencies.cursive]
version = "*"
features = ["termion-backend"]
