[package]
name = "mpv_stream"
version = "0.5.0"
edition = "2018"

[dependencies]
serde_json = "*"
curl = "*"
libmpv = "2.0.0"
toml = "*"
xdg = "*"
crossbeam = "0.7.3"
futures = "0.3"
tokio = { version = "0.3", features = ["full"] }
socket2 = "0.3.15"

[dependencies.cursive]
version = "*"
features = ["termion-backend"]

# workaround because conflict package with curl
[dependencies.miow]
socket2 = "0.3.15"
