[package]
name = "mpv_stream"
version = "0.6.0"
edition = "2018"

[dependencies]
serde_json = "1.0"
curl = "0.4"
libmpv = "2.0"
toml = "0.5"
xdg = "2.2"
futures = "0.3"
tokio = { version = "1.2", features = ["full"] }

[dependencies.cursive]
version = "0.16"
features = ["termion-backend"]
